### ISSUE TITLE
question on additional constraints

### ISSUE THREAD

**Issue by ahorvath** [mmagnus/rna-tools#103]
Dear Developer Team,

First of all, many thanks for excellent toolkit. 
We have experimental evidence that certain RNA regions are in close proximity to each other and I would like to incorporate this in the structure model.
I attached a hypothetical example with the modified (left) and original (right) structure.
![modified_vs_original_structure](https://user-images.githubusercontent.com/351654/75445541-b80e7b00-59b9-11ea-8d96-2ebe7b3b20a3.png)

Can you please help me with that?

Many thanks in advance.

**Comment by mmagnus** [comment]
Dear @ahorvath  I have missed your issue. Do you want to do it in 2D or 3D?

**Comment by ahorvath** [comment]
Dear @mmagnus, 

Both would really exciting. Do you think it is possible? Note that here base pairing is unlikely to play any part, this is facilitated by ncRNAs/proteins.

Many thanks!

**Comment by mmagnus** [comment]
for 2D I would recommend this server
http://rna.tbi.univie.ac.at/cgi-bin/RNAWebSuite/RNAfold.cgi
or
https://major.iric.ca/MC-Fold/
(you have described there how to encode your constraints)

for 3D you have to convert your distances into the correct format and fold the RNA, read this
https://genesilico.pl/SimRNAweb/doc#restraints_with_pdb

**Comment by mmagnus** [comment]
Let me know if you need more help, for now I will close this issue, is not really rna-tools related.

**Comment by ahorvath** [comment]
I will, many thanks for your help!
