### ISSUE TITLE
where is --get_simrna_ready ?

### ISSUE THREAD

**Issue by filipsPL** [mmagnus/rna-tools#106]
Hi! Is there still an option to have `--get_simrna_ready`? Some time (commits) ago there was a syntax available: `yapdb_parser.py --get_simrna_ready` and now I can't see this option in `rna_pdb_toolsx.py`.

thanks!

**Comment by filipsPL** [comment]
In the readme, there is even an example:

`$ for i in *pdb; do rna_pdb_toolsx.py --get_simrna_ready $i >  ${i/.pdb/_srr.pdb}; done`

and what I get is:

`rna_pdb_toolsx.py: error: unrecognized arguments: --get_simrna_ready`

tools installed via pip.

**Comment by mmagnus** [comment]
Hmm.. ok, wait, I'm looking for it ;-)

**Comment by mmagnus** [comment]
OK, the code says that 

`170305 Merged with get_simrna_ready and fixing OP3 terminal added`

so please use `--get-rnapuzzle-ready`, SimRNA is smart and will know what to do with rnapuzzle ready file, there is no need (in general) for `--get_simrna_ready`

     rna_pdb_toolsx.py --get-rnapuzzle-ready *pdb --inplace

**Comment by filipsPL** [comment]
It works, great, thanks! :+1:
