### ISSUE TITLE
rna_calc_inf.do_job in Jupyter Notebook: NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by mariagviegas** [mmagnus/rna-tools#110]
Dear mmagnus,

first I wanted to thank you for developing such a great package of tool for RNA analysis.

I am currently trying to calculate the INF of an unsolvated tRNA pdb with the 'rna_calc_in.do_job()' tool using Jupyter Notebook. However, when compiling my code, I get the following error: **NameError**: name 'args' is not defined. (I am attaching a screencapture of my code and the whole error message). Nevertheless, when checking the documentation, I do not know what args is or how I should define it. If you know, could you please tell me how to solve this error?

I am using Python 3.9.4, jupyter core  4.7.1 and jupyter-notebook  6.3.0.

Sorry for bothering you and thanks in advance for your help.

Best regards,
Maria Gonzalez Viegas

![mariagviegas_26 04 2021](https://user-images.githubusercontent.com/83213019/116063826-b1df6180-a685-11eb-84ef-3848fd30f68e.PNG)

**Comment by mmagnus** [comment]
Dear Maria, let me check.
