### ISSUE TITLE
Missing rna_clashscore.py

### ISSUE THREAD

**Issue by febos** [mmagnus/rna-tools#115]
Installing with "pip install -e git+http://github.com/mmagnus/rna-tools.git#egg=rna-tools"
Got an error: 
```No such file or directory: '/home/user/folder/src/rna-tools/rna_tools/tools/mq/ClashScore/rna_clashscore.py```
Fixed by renaming rna_mq_clashscore.py -> rna_clashscore.py  (is it ok?)

**Comment by mmagnus** [comment]
@febos you're right! Thanks, fixed.
