### ISSUE TITLE
rna_pdb_tools.py: command not found

### ISSUE THREAD

**Issue by akashbahai** [mmagnus/rna-tools#142]
Hi,
I have been tryimg to setup the rna-tools on my system. I have installed it using pip, but I cannot run the rna_pdb_tools.py command on terminal. I am always getting, rna_pdb_tools.py: command not found error.
Do I need to change the shebang on the top of the .py files to make it work. I have followed the instructions from here: https://rna-tools.readthedocs.io/en/latest/install-dev.html

**Comment by mmagnus** [comment]
Have you tried simply `pip install rna-tools`?

**Comment by mmagnus** [comment]
It seems both ways you should give your rna_pdb_tools.py file
https://colab.research.google.com/drive/1c4veGVwM3NLEEI0RfdUrqdBNSCYveae1?usp=sharing 

you might reload your terminal so the shell will learn where  rna_pdb_tools.py is.

**Comment by akashbahai** [comment]
Thanks for your response. It seems to be working now. The Pythonpath in .zshrc file was not set properly.

**Comment by mmagnus** [comment]
Great! Let me know if you need any more help!
