### ISSUE TITLE
`rna_pdb_tools.py  --get-ss` causes NameError.

### ISSUE THREAD

**Issue by TakumiOtagaki** [mmagnus/rna-tools#146]
After installation, when I run `rna_pdb_tools.py  --get-ss 1KPD.pdb`, I got an error.

- version: 3.20
- error command:  `rna_pdb_tools.py  --get-ss 1KPD.pdb`

The error log is as following:
```
$ rna_pdb_tools.py  --get-ss '/large/otgk/rPKExtractor/pdb/1KPD.pdb'
Traceback (most recent call last):
  File "/large/otgk/app/rna-tools/3.20/rna_tools/rna_pdb_tools.py", line 401, in <module>
    p = x3DNA(f)
        ^^^^^^^^
  File "/home/otgk/.conda/envs/pkextractor/lib/python3.11/site-packages/rna_tools/tools/rna_x3dna/rna_x3dna.py", line 79, in __init__
    self.run_x3dna(show_log)
  File "/home/otgk/.conda/envs/pkextractor/lib/python3.11/site-packages/rna_tools/tools/rna_x3dna/rna_x3dna.py", line 125, in run_x3dna
    if args.verbose: print(f'cmd: {cmd}')
       ^^^^
NameError: name 'args' is not defined
```

As for this error log, I checked the `rna_tools/tools/rna_x3dna/rna_x3dna.py` and found that
the function `run_x3dna(self, show_log=False)` should have `arg` argument.

I modified the `run_x3dna(self, show_log=False) and class x3DNA(object)` as follows:

- ↓line 76 of rna_tools/tools/rna_x3dna/rna_x3dna.py

```line 76 of rna_tools/tools/rna_x3dna/rna_x3dna.py
# def __init__(self, pdbfn, show_log=False):
def __init__(self, pdbfn, args, show_log=False):
```

 - ↓line 79 of rna_tools/tools/rna_x3dna/rna_x3dna.py
``` line 79 of rna_tools/tools/rna_x3dna/rna_x3dna.py
# self.run_x3dna(show_log)
self.run_x3dna(show_log, verbose)
```

 - ↓line 115 of rna_tools/tools/rna_x3dna/rna_x3dna.py
```line 115 of rna_tools/tools/rna_x3dna/rna_x3dna.py
# def run_x3dna(self, show_log=False):
def run_x3dna(self, verbose, show_log=False):
```

 - ↓line 125 of rna_tools/tools/rna_x3dna/rna_x3dna.py
```line 125 of rna_tools/tools/rna_x3dna/rna_x3dna.py
# if args.verbose: print(f'cmd: {cmd}')
 if verbose: print(f'cmd: {cmd}')
```

 - ↓line 401 of rna_tools/rna_pdb_tools.py
```line 401 of rna_tools/rna_pdb_tools.py
# p = x3DNA(f)
p = x3DNA(f, args.verbose)
```

then, 
```
rna_pdb_tools.py  --get-ss '/large/otgk/rPKExtractor/pdb/1KPD.pdb'
```
may work.

(I have another trouble about X3DNA, so it still remains `x3dna not found!` error. )

**Comment by mmagnus** [comment]
@TakumiOtagaki, can you try right now? I think part of the problem is that x3dna in the newer version is formatting output differently. Let me know if this works, and write the version of x3dna you're using.
