### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by marrrcin** [mmagnus/rna-tools#78]
Hi Marcin,
I wanted to use your lib, however it's impossible to install it (at least on macOS using instructions in docs). I think it's mostly due to your lib rename (from rna_pdb_tools to rna_tools). It seems like you over-engineered the whole installation process. I suggest you taking a look at standard setup tools and using simple `setup.py` to be able to install your library like any standard Python package.

**Comment by mmagnus** [comment]
Yeah, I know... now it should be much, much better, thanks Marcin for the suggestion! #105
