### ISSUE TITLE
Clanstixs problem with group and coloring

### ISSUE THREAD

**Issue by iswaryapj** [mmagnus/rna-tools#91]
python rna_clanstix.py matrix.txt --groups 400:seq1+400:seq2+400:seq3+400:seq4 --output matrix_clans.dat

The groups defined are not getting colored differently.

Please help fix the issue

**Comment by mmagnus** [comment]
[data.zip](https://github.com/mmagnus/rna-tools/files/3228826/data.zip)

**Comment by mmagnus** [comment]
![Uploading Screen Shot 2019-05-29 at 10.34.53 PM.png…]()
done :-)

**Comment by mmagnus** [comment]
<img width="810" alt="Screen Shot 2019-05-29 at 10 34 53 PM" src="https://user-images.githubusercontent.com/118740/58590522-8e76c680-8264-11e9-89d3-7d5a6c98799f.png">
done :-)
