### ISSUE TITLE
run clanstixs in multi processor

### ISSUE THREAD

**Issue by iswaryapj** [mmagnus/rna-tools#92]
Is it possible to make clanstixs work with multiprocessor.
It was taking 1 hr and 30 minutes for 1600*1600 matrix.
There are needs to do it for bigger matrices.
So making clanstixs faster by multiprocessors will save a lot of time.

Thanks in advance
Best,
Iswarya

**Comment by mmagnus** [comment]
@iswaryapj right now I don't have time to do it. It's a nice suggestion. 

You can ask someone in the lab if anyway wants to do it as an exercise.

**Comment by mmagnus** [comment]
@iswaryapj thanks for the code #95 127ef84513519414753ab74e1974d4551e6b299e
